spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db
      username: user
      password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    banner-mode: "off"
  endpoints:
    web:
      exposure:
        include: "health,info,beans,mapping"
#  sql:
#    init:
#      mode: always
  info:
    env:
      enabled: true
server:
  port: 8084
#  servlet:
#    context-path: /api
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
info:
  app:
    name: "Microservice - Best Book Application"
    description: "Microservice - Best Book Application Best Practice"
    version: "1.0.0"
#logging:
#  level:
#    root: WARN
jwt:
  issuer: test@gmail.com
  secret_key: secret
#
#producers:
#  topic1:
#    name: rental_result
#
#consumer:
#  topic1:
#    name: rental_rent
#  topic2:
#    name: rental_return
#  groupid:
#    name: book
#
#kafka:
#  bootstrapAddress: localhost:9092