version: "3.8"

services:
    mysql_db:
        image: mysql:8.0.36
        container_name: do-mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        volumes:
          - ../db/mysql/migrations:/docker-entrypoint-initdb.d

    redis_db:
        image: redis:7.2.4
        container_name: do-redis
        restart: always
        ports:
          - "6379:6379"
        deploy:
          resources:
            limits:
              cpus: "1"
              memory: 1024M